### ISSUE TITLE
Breaks Swagger API

### ISSUE THREAD

**Issue by jdrew82** [vapor-ware/netbox-virtual-circuit-plugin#22]
It appears that this plugin is causing the Swagger API interface to bomb. Upon doing some investigation it seems like your VLAN serializer is using the same ref_name as the actual VLAN serializer.

"Schema for <class 'spam.api.serializers.VLANSerializer'> would override distinct serializer <class 'netbox_virtual_circuit_plugin.api.serializers.VLANSerializer'> because they implicitly share the same ref_name; explicitly set the ref_name atribute on both serializers' Meta classes"

**Comment by hoanhan101** [comment]
Thanks for looking into this. I have fixed this issue since the `0.1.4` release. I'm using the latest version `0.2.0` and it seems to have no problem as well.
