### ISSUE TITLE
Add VCID plugin info inside "Change Log"

### ISSUE THREAD

**Issue by jinaloo7** [vapor-ware/netbox-virtual-circuit-plugin#31]
I think it will be a good add if we can showcase logs related to VCID plugin inside Change Log on Netbox UI.what you guys think? @marcoceppi @edaniszewski @hoanhan101

**Comment by marcoceppi** [comment]
This should be as simple as changing those models to a `ChangeLoggedModel` and running the migrations then adding the UI. It's a nice idea to help track changes from within the Netbox UI though 99% of our changes will be from an automated user

**Comment by hoanhan101** [comment]
Yes as @marcoceppi said this should be pretty simple and straightforward. Should have a PR up and ready either by the end of this week or early next week.
