### ISSUE TITLE
netbox:: ChangeLoggedModel has moved location and is now in extras

### ISSUE THREAD

**Issue by mystery-rabbit** [vapor-ware/netbox-virtual-circuit-plugin#37]
Netbox have moved the location of the ChangeLoggedModel ;

See [ Commit. ](https://github.com/netbox-community/netbox/commit/8d7001fe565e4f1a3d14893b89e89cd3e8558346)

upshot is that I am not able to import this plugin in v2.9.3 of netbox ( potentially all >2.9.0 ? )

**Comment by hoanhan101** [comment]
Thanks for looking into it. We're working on the fix here at #38. Let me know if you have any thoughts/comments/suggestions.

**Comment by mystery-rabbit** [comment]
Confirmed tested and working ; Netbox v2.9.4 and netbox-virtual-circuit-plugin v1.1.1;
Good work; Thanks
