### ISSUE TITLE
Add a box for Virtual Circuits in the tenant information screen.

### ISSUE THREAD

**Issue by marcoceppi** [vapor-ware/netbox-virtual-circuit-plugin#40]
It would be great if we could extend the Stats pane in the tenant information screen to include the count of Virtual Circuits a tenant is a member of based on their VLAN assignment
![Selection_164](https://user-images.githubusercontent.com/70613/93912979-75541d80-fcd2-11ea-9641-e7c3cf60fc5d.png)

**Comment by hoanhan101** [comment]
@marcoceppi I've looked into this and it seems like extending the stats panel requires modifying NetBox's code. What this plugin can do instead is to add a separate panel like one below:

![image](https://user-images.githubusercontent.com/12986752/97627205-68c59200-1a01-11eb-9299-4d5c4d908eb9.png)

**Comment by marcoceppi** [comment]
Works for me, I'd expect to jist see Virtual Circuit and not assigned vlans
