### ISSUE TITLE
Netbox extras.models error

### ISSUE THREAD

**Issue by Phied** [vapor-ware/netbox-virtual-circuit-plugin#56]
I kept getting error unable to load module from extras.models ChangeLoggedModel.

Looks like Netbox has updated this to be netbox.ChangeLoggedModel instead of extras.

**Comment by wols** [comment]
After update from netbox `2.11.0` to `2.11.3` the error was gone.

**Comment by hiddenman** [comment]
> I kept getting error unable to load module from extras.models ChangeLoggedModel.
> 
> Looks like Netbox has updated this to be netbox.ChangeLoggedModel instead of extras.

Hi,

The same error here.

@Phied Have you fixed it? Does simple changing model path fixes the error?

Thank you.

**Comment by hiddenman** [comment]
No, it does not:

ERRORS:
netbox_virtual_circuit_plugin.VirtualCircuit: (models.E026) The model cannot have more than one field with 'primary_key=True'.

So the plugin should be updated.  @wols @hoanhan101 @marcoceppi   Guys, could you please take a look?

Thank you.
