### ISSUE TITLE
Assigning a Virtual Circuit to 2 VLANs in a single API request

### ISSUE THREAD

**Issue by hoanhan101** [vapor-ware/netbox-virtual-circuit-plugin#9]
As in version `0.1.3`, in order to assign a Virtual Circuit to 2 VLANs, one needs to call the API twice as the plugin only supports assigning 1 Virtual Circuit to 1 VLAN in 1 request. Behind the scene, Virtual-Circuit-to-VLAN connections/models are stored in a separate 2-column database table where VLAN ID is the primary key. That said, in order to have a Virtual Circuit connected to 2 VLANS, one way is to have 2 Virtual-Circuit-to-VLAN connections registered in the same table. As [Django's Serializers](https://www.django-rest-framework.org/api-guide/serializers/) directly serializes these models to native Python types that are renderable in JSON, this translates to 2 API requests that are able to register 2 connections in the table. This implementation is simple and straightforward enough as it does the job and can scale fine if in the future we want a Virtual Circuit to connect to more than 2 VLANs.  The one downside that we (me, @marcoceppi and @jinaloo7) agree on is that it takes 2 API requests to assign 2 VLANs that eventually make up a meaningful Virtual Circuit. It would be ideal if we could assign 2 VLANs in a single request.

Another way to have a Virtual Circuit connected to 2 VLANS is to modify our models so that we have a 3-column table instead of a 2-column one, where 1 Virtual Circuit must hold 2 VLANs connections. This way we don't mess with Django's Serializers but still end up with an API endpoint that is able to register 2 VLANs using a single request. However, in order to have a 3-column table that satisfies our uniqueness constraints (when a VLAN is assigned to a Virtual Circuit, it can not exist in another Virtual Circuit without first being removed), both VLANs fields must be primary keys. [This is not currently supported in Django and also, there is still no good way to get around it.](https://code.djangoproject.com/ticket/373?cversion=0&cnum_hist=130)

Let me know if you have better ideas on how to go about this. As for me, I think it's fine to keep what we have as it is now so it doesn't block some work over the Network API. And since we have more control of the Network API as we build one from scratch, a possible workaround is to combine 2 API calls to the plugin in a single call so that the consumer of Network API only needs to call it once.

**Comment by marcoceppi** [comment]
It's also possible to have more than 2 vlans in a virtual circuit. While we won't support that configuration at Vapor, it doesn't make it any less valid

**Comment by jinaloo7** [comment]
Yes I totally agree and think it is not necessary at this moment to do.The initial version of VCID itself works fine and solves the problem of having VCID in netbox.

**Comment by marcoceppi** [comment]
There are ways to produce custom serializers so that you can set "fk" data
by passing in pls of the lookup field. I'll see if I can find an example

**Comment by hoanhan101** [comment]
There's a way to [write over a nested serializer](https://www.django-rest-framework.org/api-guide/relations/#writable-nested-serializers) that I think could work as well. Let me do some experimenting then I'll let you know.
